version: "3.8"

volumes:
  rabbitmq_data:

services:
 
  ###################################
  # Order: The Order microservice
  ###################################
  # order:
  #   build:
  #     context: ./
  #     dockerfile: order.inventory.Dockerfile
  #   image: tame123/order:esd
  #   restart: always
  #   environment:
  #     dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/order
  #     PYTHONUNBUFFERED: 1
 
  #######################################################
  # Shipping Record: The Shipping Record microservice
  #######################################################
  # shipping_record:
  #   build:
  #     context: ./
  #     dockerfile: shipping_record.inventory.Dockerfile
  #   image: tame123/shipping_record:esd
  #   restart: always
  #   environment:
  #     PYTHONUNBUFFERED: 1

  ####################################
  # RabbitMQ: The messaging broker   
  # Completed
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq
      
  #################################################
  # Notification: The Notification microservice
  # Completed
  #################################################
  notification:
    build:
      context: ./notification
      dockerfile: notification.Dockerfile
    image: tame123/notification:1.0
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  ###################################
  # Error: The Error microservice
  ###################################
  # error:
  #   build:
  #     context: ./
  #     dockerfile: error.inventory.Dockerfile
  #   image: tame123/error:esd
  #   restart: always
  #   depends_on:
  #     - rabbitmq
  #   environment:
  #     rabbit_host: rabbitmq
  #     rabbit_port: 5672
  #     PYTHONUNBUFFERED: 1

  ###############################################
  # Place Order: The Place Order microservice
  ###############################################
  # place_order:
  #   build:
  #     context: ./
  #     dockerfile: place_order.inventory.Dockerfile
  #   image: tame123/place_order:esd
  #   restart: always
  #   depends_on:
  #     - order
  #     - shipping_record
  #     - activity_log
  #     - error
  #     - rabbitmq
  #   environment:
  #     rabbit_host: rabbitmq
  #     rabbit_port: 5672
  #     order_URL: http://order:5001/order
  #     shipping_record_URL: http://shipping_record:5002/shipping_record 
  #     PYTHONUNBUFFERED: 1
  #   ports:
  #     - "5100:5100"

  ##################################
  # Book: The Book microservice
  ##################################
  # book:
  #   build:
  #     context: ./
  #     dockerfile: book.inventory.Dockerfile
  #   image: tame123/book:esd
  #   restart: always
  #   environment:
  #     dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/book
  #     PYTHONUNBUFFERED: 1
  #   ports:
  #     - "5000:5000"


  ##################################
  # WIP
  ##################################
  # cart:
  #   build:
  #     context: ./cart
  #     dockerfile: cart.Dockerfile
  #   image: bellekwang/cart:1.0
  #   restart: always
  #   environment:
  #     dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/cart
  #     PYTHONUNBUFFERED: 1
  #   ports:
  #     - "5000:5000"
      



  # ###############################################
  # # WIP
  # # Checkout: Checkout microservice
  # ###############################################
  checkout:
    build:
      context: ./checkout
      dockerfile: checkout.Dockerfile
    image: tame123/checkout:1.0
    restart: always
    depends_on:
      - cart_placeholder
      - inventory_placeholder
      # - payment
      - rabbitmq
      # - order_history
      - notification
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      inventory_URL: http://inventory_placeholder:5552/inventory
      cart_URL: http://cart_placeholder:5000/cart
      PYTHONUNBUFFERED: 1
    ports:
      - "5550:5550"

  # ###############################################
  # placeholder cart and inventory
  # ###############################################
  inventory_placeholder:
    build:
      context: ./checkout
      dockerfile: inventory.Dockerfile
    image: tame123/inventory:1.0
    restart: always
    environment:
      PYTHONUNBUFFERED: 1

  cart_placeholder:
    build:
      context: ./checkout
      dockerfile: cart.Dockerfile
    image: tame123/cart:1.0
    restart: always
    environment:
      PYTHONUNBUFFERED: 1