version: "3.8"

services:

  inventory:
    build:
      context: ./
      dockerfile: inventory.Dockerfile
    image: brad/inventory:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root:@localhost:3306/inventory
      PYTHONUNBUFFERED: 1
    ports:
      - "5552:5552"