version: "3.8"

services:

  cart:
    build:
      context: ./
      dockerfile: cart.Dockerfile
    image: bellekwang/cart:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/cart
      PYTHONUNBUFFERED: 1
    ports:
      - "5000:5000"
      

